ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production" 
  hosts:
    - name: chartmuseum.34.72.26.137.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.34.72.26.137.nip.io
securityContext: {}
env:
    open:
        DISABLE_API: false