apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: israodin@gmail.com
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
    - http01:
        ingress:
          class:  nginx