---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production" 
spec:
  tls:
  - hosts:
    - shop.104.154.141.175.nip.io
    secretName: shop.104.154.141.175.nip.io
  rules:
  - host: shop.104.154.141.175.nip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort:  8080