apiVersion: v1
kind: Pod
metadata: 
    name: hw-web
    labels:
        app: hw-web
spec:
    containers:
    - name: hw-web
      image: israodin/otus_kube:v0.0.1-intro
      volumeMounts:
      - name: app
        mountPath: /app    
    initContainers:
    - name: init-web
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app  
    volumes:
    - name: app
      emptyDir: {}